id: P1EA8FDDF
initial_creation_type: input
source_metadata:
  title: Bhāmati a commentary on Śaṃkara's Brahmasūtrabhāṣya
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vedānta
  data entry: members of the Sansknet Project
  contribution to GRETIL: members of the Sansknet Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:56:41.263427'
last_modified_at: '2022-03-09T14:56:41.263441'
